# Generated by Django 5.2.4 on 2025-08-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakeorder',
            old_name='words',
            new_name='phrase',
        ),
        migrations.AddField(
            model_name='cakeorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
