# Generated by Django 5.2.4 on 2025-08-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_rename_words_cakeorder_phrase_cakeorder_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakeorder',
            old_name='phrase',
            new_name='phrase_on_cake',
        ),
    ]
