# Generated by Django 5.2.4 on 2025-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_rename_phrase_cakeorder_phrase_on_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeberries',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cakedecor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cakeform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cakelevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caketopping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
