# Generated by Django 5.2.4 on 2025-08-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_cakeberries_is_active_cakedecor_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakelevel',
            old_name='level',
            new_name='name',
        ),
    ]
