# Generated by Django 5.2.4 on 2025-09-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeorder',
            name='adv_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
