# Generated by Django 5.2.4 on 2025-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_cakeorder_adv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeorder',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
