# Generated by Django 5.2.4 on 2025-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_cakeorder_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeorder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
